'use strict';
const query=document.getElementById('query'),results=document.getElementById('results'),overlay=document.getElementById('overlay');
const entries=[['今天','新建任务','开始一个新的会话'],['今天','创建 Pi-Desktop 主题插件','PI-Desktop-Sax-Theme'],['今天','Phase 1 · 协议边界与架构决策','PI-Desktop 插件开发'],['更早','研究粒子溶解与弹窗退出','Sax Design Vue'],['更早','整理项目与会话归档','工作空间'],['命令','New task','创建任务'],['命令','Compact conversation context','压缩会话上下文']];
let selected=0;
function close(){overlay.hidden=true;document.getElementById('reopen').focus();}
function draw(){results.replaceChildren();let lastGroup='';const filtered=entries.filter(e=>e.join(' ').toLowerCase().includes(query.value.toLowerCase()));selected=Math.min(selected,Math.max(0,filtered.length-1));filtered.forEach((entry,index)=>{if(entry[0]!==lastGroup){const label=document.createElement('div');label.className='search-group-label';label.textContent=entry[0];results.append(label);lastGroup=entry[0];}const row=document.createElement('button');row.className='search-item'+(index===selected?' active':'');row.type='button';const icon=document.createElement('span');icon.className='search-item-icon';icon.textContent=entry[0]==='命令'?'⌘':'▢';const detail=document.createElement('span');detail.className='search-session-details';const title=document.createElement('span');title.className='search-item-title';title.textContent=entry[1];const meta=document.createElement('span');meta.className='search-item-meta';meta.textContent=entry[2];detail.append(title,meta);row.append(icon,detail);row.onclick=()=>{document.getElementById('selection').textContent=`预览选择：${entry[1]}`;close();};results.append(row);});if(!filtered.length){const empty=document.createElement('div');empty.className='search-empty';empty.textContent='没有匹配的结果，试试其他关键词';results.append(empty);}}
query.oninput=()=>{selected=0;draw();};
query.addEventListener('keydown',e=>{const count=results.querySelectorAll('.search-item').length;if((e.key==='ArrowDown'||e.key==='ArrowUp')&&count){e.preventDefault();selected=(selected+(e.key==='ArrowDown'?1:-1)+count)%count;draw();results.querySelector('.active')?.scrollIntoView({block:'nearest'});}if(e.key==='Enter'){e.preventDefault();results.querySelector('.active')?.click();}});
document.getElementById('close').onclick=close;document.getElementById('reopen').onclick=()=>{overlay.hidden=false;query.focus();};overlay.onclick=e=>{if(e.target===overlay)close();};
document.addEventListener('keydown',e=>{if(overlay.hidden)return;if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const controls=[...overlay.querySelectorAll('input,button')];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
document.getElementById('mode').onclick=()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';document.getElementById('theme').href=`../themes/sax-${dark?'dark':'light'}.css`;document.getElementById('mode').textContent=dark?'浅色':'深色';};draw();query.focus();
